version: '3'

services:
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    networks:
      - nginx_network

  djangoapp:
    build: .
    restart: always
    volumes:
      - .:/code
      - .:/opt/services/djangoapp/src
      - static_volume:/static/django/
      - media_volume:/app/media/django/
      - ./submits:/media/submits/
      - ./round-data:/media/round-data/
    networks:
      - nginx_network

    depends_on:
      - db
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  nginx:
    image: nginx:1.21.3-alpine
    ports:
      - 80:80
    volumes:
      - ./config/nginx/conf.d:/etc/nginx/conf.d
      - static_volume:/var/html/static/django
      - media_volume:/var/html/media/django/
    depends_on:
      - djangoapp
    networks:
      - nginx_network

networks:
  nginx_network:
    driver: bridge

volumes:
  static_volume:
  media_volume:
