# Generated by Django 4.1.3 on 2022-12-10 14:36

import datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 10, 14, 36, 58, 34379)),
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=30)),
                ('created_at', models.DateTimeField(default=datetime.datetime(2022, 12, 10, 14, 36, 58, 37410))),
                ('finish_at', models.DateTimeField(default=datetime.datetime(2022, 12, 11, 14, 36, 58, 37452))),
                ('is_active', models.BooleanField(default=True)),
                ('players', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
