# Generated by Django 4.1.3 on 2022-12-11 21:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_user_created_at_game'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 11, 21, 29, 42, 393213)),
        ),
        migrations.AlterField(
            model_name='game',
            name='finish_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 12, 21, 29, 42, 393269)),
        ),
        migrations.AlterField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 11, 21, 29, 42, 4942)),
        ),
    ]
