# Generated by Django 4.1.3 on 2023-02-01 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_submit'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='logo',
            field=models.FileField(null=True, upload_to='submits'),
        ),
    ]
