# Generated by Django 4.1.3 on 2023-01-21 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_submit_delete_resume'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submit',
            name='email',
        ),
        migrations.RemoveField(
            model_name='submit',
            name='name',
        ),
    ]
