# Generated by Django 4.1.3 on 2023-02-06 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_round_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='round',
            name='data_of_round',
            field=models.FileField(null=True, upload_to='round_data'),
        ),
    ]
