# Generated by Django 4.1.3 on 2023-02-16 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_round_data_of_round'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='round',
            name='data',
        ),
        migrations.AddField(
            model_name='game',
            name='datetime_end',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='datetime_start',
            field=models.DateTimeField(null=True),
        ),
    ]
