# Generated by Django 4.1.3 on 2023-03-28 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_user_first_last_name_allow_null'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='round',
            name='data',
        ),
    ]
