# Generated by Django 4.1.3 on 2023-05-01 16:54

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_teams_and_teamapplications'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='round',
            name='data',
        ),
        migrations.AddField(
            model_name='submit',
            name='create_at',
            field=models.DateTimeField(default=datetime.datetime(1, 1, 1, 0, 0)),
        ),
        migrations.AddField(
            model_name='submit',
            name='final',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='submit',
            name='score',
            field=models.FloatField(default=0),
        ),
        migrations.CreateModel(
            name='MemberApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.PositiveSmallIntegerField(default=0)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.team')),
            ],
        ),
    ]
