# Generated by Django 4.1.3 on 2023-05-03 11:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_teams_and_teamapplications'),
    ]

    operations = [
        migrations.AddField(
            model_name='round',
            name='round_target',
            field=models.FileField(null=True, upload_to='round_target'),
        ),
        migrations.AddField(
            model_name='submit',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='submit',
            name='score',
            field=models.FloatField(null=True),
        ),
    ]
